---

- hosts: all,!proxy
  vars:
    cloudera_mirror_host: "archive.cloudera.com"
    centos_mirror_host: "mirror.optus.net"
  tasks:
    - name: Configure CDH5 YUM Repository 
      yum_repository:
        name: "cloudera-cdh5"
        description: "Cloudera's Distribution for Hadoop, Version 5"
        baseurl: "http://{{ cloudera_mirror_host }}/cdh5/redhat/6/x86_64/cdh/5.3.8/"
        gpgkey: "http://{{ cloudera_mirror_host }}/cdh5/redhat/6/x86_64/cdh/RPM-GPG-KEY-cloudera"
        gpgcheck: yes

    - name: Configure Cloudera Manager YUM Repository
      yum_repository:
        name: "cloudera-manager"
        description: "Cloudera Manager"
        baseurl: "http://{{ cloudera_mirror_host }}/cm5/redhat/6/x86_64/cm/5.3.8/"
        gpgkey: "http://{{ cloudera_mirror_host }}/cm5/redhat/6/x86_64/cm/RPM-GPG-KEY-cloudera"
        gpgcheck: yes

    - name: Configure CentOS Base Repository
      yum_repository:
        name: "base"
        description: "CentOS-$releasever - Base"
        baseurl: "http://{{ centos_mirror_host }}/centos/$releasever/os/$basearch/"
        gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6"
        gpgcheck: yes
        file: "CentOS-Base"

    - name: Configure CentOS Updates Repository
      yum_repository:
        name: "updates"
        description: "CentOS-$releasever - Updates"
        baseurl: "http://{{ centos_mirror_host }}/centos/$releasever/updates/$basearch/"
        gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6"
        gpgcheck: yes
        file: "CentOS-Base"

    - name: Configure CentOS Extras Repository 
      yum_repository:
        name: "extras"
        description: "CentOS-$releasever - Extras"
        baseurl: "http://{{ centos_mirror_host }}/centos/$releasever/extras/$basearch/"
        gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6"
        gpgcheck: yes
        file: "CentOS-Base"

    - shell: echo {{ item }} >> /etc/hosts
      with_items: 
        - "{{ hostvars['proxy']['ansible_eth0']['ipv4']['address'] }}    mirror.optus.net"
        - "{{ hostvars['proxy']['ansible_eth0']['ipv4']['address'] }}    archive.cloudera.com"
      #FIXME

    - name: Install Oracle J2 SDK 
      yum:
        name: "oracle-j2sdk1.7"
        state: present
