---

# Start Docker Containers
- include: containers.yml

# Install and configure Proxy
- include: proxy.yml

# Configure YUM repositories
- include: base.yml

# Install and configure HDFS
- include: hdfs.yml

# Install and configure YARN
- include: yarn.yml
